2022-06-28 14:42:47,327 INFO    MainThread:13420 [wandb_setup.py:_flush():76] Loading settings from /home/harshil/.config/wandb/settings
2022-06-28 14:42:47,328 INFO    MainThread:13420 [wandb_setup.py:_flush():76] Loading settings from /home/harshil/work/simgan_lti/wandb/settings
2022-06-28 14:42:47,328 INFO    MainThread:13420 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-06-28 14:42:47,328 WARNING MainThread:13420 [wandb_setup.py:_flush():76] Could not find program at -m third_party.a2c_ppo_acktr.main_gail_dyn_ppo
2022-06-28 14:42:47,328 INFO    MainThread:13420 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program': '-m third_party.a2c_ppo_acktr.main_gail_dyn_ppo'}
2022-06-28 14:42:47,328 INFO    MainThread:13420 [wandb_init.py:_log_setup():428] Logging user logs to /home/harshil/work/simgan_lti/wandb/run-20220628_144247-1bup5glq/logs/debug.log
2022-06-28 14:42:47,328 INFO    MainThread:13420 [wandb_init.py:_log_setup():429] Logging internal logs to /home/harshil/work/simgan_lti/wandb/run-20220628_144247-1bup5glq/logs/debug-internal.log
2022-06-28 14:42:47,328 INFO    MainThread:13420 [wandb_init.py:init():462] calling init triggers
2022-06-28 14:42:47,329 INFO    MainThread:13420 [wandb_init.py:init():465] wandb.init called with sweep_config: {}
config: {}
2022-06-28 14:42:47,329 INFO    MainThread:13420 [wandb_init.py:init():515] starting backend
2022-06-28 14:42:47,329 INFO    MainThread:13420 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-06-28 14:42:47,344 INFO    MainThread:13420 [backend.py:ensure_launched():217] starting backend process...
2022-06-28 14:42:47,353 INFO    MainThread:13420 [backend.py:ensure_launched():222] started backend process with pid: 13432
2022-06-28 14:42:47,355 INFO    MainThread:13420 [wandb_init.py:init():525] backend started and connected
2022-06-28 14:42:47,367 INFO    MainThread:13420 [wandb_init.py:init():596] updated telemetry
2022-06-28 14:42:47,386 INFO    MainThread:13420 [wandb_init.py:init():627] communicating run to backend with 30 second timeout
2022-06-28 14:43:17,387 INFO    MainThread:13420 [interface_shared.py:_communicate_run():326] couldn't get run from backend
2022-06-28 14:43:17,387 ERROR   MainThread:13420 [wandb_init.py:init():636] backend process timed out
2022-06-28 14:43:17,387 ERROR   MainThread:13420 [wandb_init.py:init():647] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-06-28 14:43:17,399 ERROR   MainThread:13420 [wandb_init.py:init():1026] error
Traceback (most recent call last):
  File "/home/harshil/anaconda3/envs/drones/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 999, in init
    run = wi.init()
  File "/home/harshil/anaconda3/envs/drones/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 651, in init
    backend.cleanup()
  File "/home/harshil/anaconda3/envs/drones/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 246, in cleanup
    self.interface.join()
  File "/home/harshil/anaconda3/envs/drones/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 475, in join
    super().join()
  File "/home/harshil/anaconda3/envs/drones/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 666, in join
    _ = self._communicate_shutdown()
  File "/home/harshil/anaconda3/envs/drones/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 472, in _communicate_shutdown
    _ = self._communicate(record)
  File "/home/harshil/anaconda3/envs/drones/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/harshil/anaconda3/envs/drones/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 231, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
